/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/Flutter_0917_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Flutter_0917_icons {
  Flutter_0917_icons._();

  static const _kFontFam = 'Flutter_0917_icons';

  static const IconData add___ = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData output = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData number___ = const IconData(0xe805, fontFamily: _kFontFam);
}
