/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/Flutter_0824_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Flutter_0824_icons {
  Flutter_0824_icons._();

  static const _kFontFam = 'Flutter_0824_icons';

  static const IconData tags_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add___ = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData doc = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData tags = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData work_location = const IconData(0xe806, fontFamily: _kFontFam);
}
