/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Flutter_1101 {
  Flutter_1101._();

  static const _kFontFam = 'Flutter_1101';

  static const IconData add____5 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData add____6 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData add____7 = const IconData(0xe815, fontFamily: _kFontFam);
}
