/// Flutter icons GCIcon
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GCIcon
///      fonts:
///       - asset: fonts/GCIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GCIcon {
  GCIcon._();

  static const _kFontFam = 'GCIcon';

  static const IconData description = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData favorite_activities = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData gender = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData job = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData volunter = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData work_location = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData meet = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData b_day = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData marital_status = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData religion = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData website = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData hub = const IconData(0xe812, fontFamily: _kFontFam);
}
